services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: vini
      POSTGRES_PASSWORD: rafael98
      POSTGRES_DB: DB_desafio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_ui
    user: root
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: viniciusrob2006m@gmail.com
      PGADMIN_DEFAULT_PASSWORD: rafael98
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data: